# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SimMotion.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDial,
    QGroupBox, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QSlider, QTabWidget, QTextBrowser,
    QWidget)

class Ui_SimMotion(object):
    def setupUi(self, SimMotion):
        if not SimMotion.objectName():
            SimMotion.setObjectName(u"SimMotion")
        SimMotion.resize(650, 615)
        SimMotion.setMinimumSize(QSize(650, 615))
        SimMotion.setMaximumSize(QSize(650, 615))
        self.btn_motion = QPushButton(SimMotion)
        self.btn_motion.setObjectName(u"btn_motion")
        self.btn_motion.setGeometry(QRect(150, 10, 121, 71))
        font = QFont()
        font.setPointSize(12)
        self.btn_motion.setFont(font)
        self.btn_motion.setCheckable(True)
        self.lbl_title = QLabel(SimMotion)
        self.lbl_title.setObjectName(u"lbl_title")
        self.lbl_title.setGeometry(QRect(280, 10, 181, 21))
        font1 = QFont()
        font1.setPointSize(16)
        font1.setBold(True)
        self.lbl_title.setFont(font1)
        self.lbl_version = QLabel(SimMotion)
        self.lbl_version.setObjectName(u"lbl_version")
        self.lbl_version.setGeometry(QRect(280, 35, 171, 16))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setItalic(False)
        self.lbl_version.setFont(font2)
        self.lbl_logo = QLabel(SimMotion)
        self.lbl_logo.setObjectName(u"lbl_logo")
        self.lbl_logo.setGeometry(QRect(430, 10, 211, 111))
        self.lbl_logo.setStyleSheet(u"background: transparent;")
        self.lbl_logo.setPixmap(QPixmap(u"images/r22_transparent_211.png"))
        self.tabWidget = QTabWidget(SimMotion)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 90, 631, 441))
        self.tabWidget.setFont(font)
        self.tab_main = QWidget()
        self.tab_main.setObjectName(u"tab_main")
        self.groupBox = QGroupBox(self.tab_main)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 0, 171, 181))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 150, 90, 20))
        self.label_7.setFont(font)
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 30, 90, 20))
        self.label_10.setFont(font)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 90, 90, 20))
        self.label_5.setFont(font)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 60, 90, 20))
        self.label_4.setFont(font)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 120, 90, 20))
        self.label_6.setFont(font)
        self.lbl_sim_pitch = QLabel(self.groupBox)
        self.lbl_sim_pitch.setObjectName(u"lbl_sim_pitch")
        self.lbl_sim_pitch.setGeometry(QRect(110, 60, 49, 21))
        self.lbl_sim_pitch.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.lbl_sim_roll = QLabel(self.groupBox)
        self.lbl_sim_roll.setObjectName(u"lbl_sim_roll")
        self.lbl_sim_roll.setGeometry(QRect(110, 90, 49, 21))
        self.lbl_sim_roll.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.lbl_sim_yaw = QLabel(self.groupBox)
        self.lbl_sim_yaw.setObjectName(u"lbl_sim_yaw")
        self.lbl_sim_yaw.setGeometry(QRect(110, 120, 49, 21))
        self.lbl_sim_yaw.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.lbl_sim_speed = QLabel(self.groupBox)
        self.lbl_sim_speed.setObjectName(u"lbl_sim_speed")
        self.lbl_sim_speed.setGeometry(QRect(110, 150, 49, 21))
        self.lbl_sim_speed.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.lbl_sim_update = QLabel(self.groupBox)
        self.lbl_sim_update.setObjectName(u"lbl_sim_update")
        self.lbl_sim_update.setGeometry(QRect(110, 30, 49, 21))
        self.lbl_sim_update.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.groupBox_2 = QGroupBox(self.tab_main)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(180, 0, 291, 181))
        self.label_11 = QLabel(self.groupBox_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 30, 171, 20))
        self.label_11.setFont(font)
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 90, 171, 20))
        self.label_12.setFont(font)
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 60, 171, 20))
        self.label_13.setFont(font)
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 120, 171, 20))
        self.label_15.setFont(font)
        self.lbl_motion_update = QLabel(self.groupBox_2)
        self.lbl_motion_update.setObjectName(u"lbl_motion_update")
        self.lbl_motion_update.setGeometry(QRect(170, 30, 49, 21))
        self.lbl_motion_update.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.lbl_motion_timestamp = QLabel(self.groupBox_2)
        self.lbl_motion_timestamp.setObjectName(u"lbl_motion_timestamp")
        self.lbl_motion_timestamp.setGeometry(QRect(230, 30, 49, 21))
        self.lbl_motion_timestamp.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.lbl_motion_pitch = QLabel(self.groupBox_2)
        self.lbl_motion_pitch.setObjectName(u"lbl_motion_pitch")
        self.lbl_motion_pitch.setGeometry(QRect(170, 60, 49, 21))
        self.lbl_motion_pitch.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.lbl_motion_roll = QLabel(self.groupBox_2)
        self.lbl_motion_roll.setObjectName(u"lbl_motion_roll")
        self.lbl_motion_roll.setGeometry(QRect(170, 90, 49, 21))
        self.lbl_motion_roll.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.lbl_motion_yaw = QLabel(self.groupBox_2)
        self.lbl_motion_yaw.setObjectName(u"lbl_motion_yaw")
        self.lbl_motion_yaw.setGeometry(QRect(170, 120, 49, 21))
        self.lbl_motion_yaw.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.lbl_motion_pitch_rate = QLabel(self.groupBox_2)
        self.lbl_motion_pitch_rate.setObjectName(u"lbl_motion_pitch_rate")
        self.lbl_motion_pitch_rate.setGeometry(QRect(230, 60, 49, 21))
        self.lbl_motion_pitch_rate.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.lbl_motion_roll_rate = QLabel(self.groupBox_2)
        self.lbl_motion_roll_rate.setObjectName(u"lbl_motion_roll_rate")
        self.lbl_motion_roll_rate.setGeometry(QRect(230, 90, 49, 21))
        self.lbl_motion_roll_rate.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.lbl_motion_yaw_rate = QLabel(self.groupBox_2)
        self.lbl_motion_yaw_rate.setObjectName(u"lbl_motion_yaw_rate")
        self.lbl_motion_yaw_rate.setGeometry(QRect(230, 120, 49, 21))
        self.lbl_motion_yaw_rate.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.groupBox_4 = QGroupBox(self.tab_main)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(480, 0, 141, 181))
        self.label_19 = QLabel(self.groupBox_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 60, 71, 20))
        self.label_19.setFont(font)
        self.label_20 = QLabel(self.groupBox_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 30, 71, 20))
        self.label_20.setFont(font)
        self.label_21 = QLabel(self.groupBox_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 90, 71, 20))
        self.label_21.setFont(font)
        self.lbl_IMU_pitch = QLabel(self.groupBox_4)
        self.lbl_IMU_pitch.setObjectName(u"lbl_IMU_pitch")
        self.lbl_IMU_pitch.setGeometry(QRect(80, 30, 49, 21))
        self.lbl_IMU_pitch.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.lbl_IMU_roll = QLabel(self.groupBox_4)
        self.lbl_IMU_roll.setObjectName(u"lbl_IMU_roll")
        self.lbl_IMU_roll.setGeometry(QRect(80, 60, 49, 21))
        self.lbl_IMU_roll.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.lbl_IMU_yaw = QLabel(self.groupBox_4)
        self.lbl_IMU_yaw.setObjectName(u"lbl_IMU_yaw")
        self.lbl_IMU_yaw.setGeometry(QRect(80, 90, 49, 21))
        self.lbl_IMU_yaw.setStyleSheet(u"background-color: black; color: lime; border: 1px solid #00FF00;")
        self.grp_axes = QGroupBox(self.tab_main)
        self.grp_axes.setObjectName(u"grp_axes")
        self.grp_axes.setGeometry(QRect(0, 190, 471, 211))
        self.sld_roll = QSlider(self.grp_axes)
        self.sld_roll.setObjectName(u"sld_roll")
        self.sld_roll.setGeometry(QRect(100, 50, 31, 151))
        self.sld_roll.setMinimum(-15)
        self.sld_roll.setMaximum(15)
        self.sld_roll.setTickPosition(QSlider.TickPosition.TicksBothSides)
        self.sld_roll.setTickInterval(5)
        self.sld_yaw = QDial(self.grp_axes)
        self.sld_yaw.setObjectName(u"sld_yaw")
        self.sld_yaw.setEnabled(False)
        self.sld_yaw.setGeometry(QRect(150, 50, 141, 151))
        self.sld_yaw.setMaximum(360)
        self.sld_yaw.setValue(180)
        self.sld_yaw.setWrapping(True)
        self.sld_yaw.setNotchTarget(10.000000000000000)
        self.sld_yaw.setNotchesVisible(True)
        self.sld_pitch = QSlider(self.grp_axes)
        self.sld_pitch.setObjectName(u"sld_pitch")
        self.sld_pitch.setGeometry(QRect(30, 50, 31, 151))
        self.sld_pitch.setMinimum(-19)
        self.sld_pitch.setMaximum(23)
        self.sld_pitch.setTickPosition(QSlider.TickPosition.TicksBothSides)
        self.sld_pitch.setTickInterval(5)
        self.lbl_sld_pitch = QLabel(self.grp_axes)
        self.lbl_sld_pitch.setObjectName(u"lbl_sld_pitch")
        self.lbl_sld_pitch.setGeometry(QRect(50, 20, 21, 16))
        self.lbl_sld_roll = QLabel(self.grp_axes)
        self.lbl_sld_roll.setObjectName(u"lbl_sld_roll")
        self.lbl_sld_roll.setGeometry(QRect(130, 20, 21, 16))
        self.lbl_sld_yaw = QLabel(self.grp_axes)
        self.lbl_sld_yaw.setObjectName(u"lbl_sld_yaw")
        self.lbl_sld_yaw.setEnabled(False)
        self.lbl_sld_yaw.setGeometry(QRect(220, 20, 31, 16))
        self.btn_home = QPushButton(self.grp_axes)
        self.btn_home.setObjectName(u"btn_home")
        self.btn_home.setGeometry(QRect(310, 150, 121, 51))
        self.btn_home.setFont(font)
        self.btn_home.setCheckable(True)
        self.btn_axes = QPushButton(self.grp_axes)
        self.btn_axes.setObjectName(u"btn_axes")
        self.btn_axes.setGeometry(QRect(310, 90, 121, 51))
        self.btn_axes.setFont(font)
        self.btn_axes.setCheckable(True)
        self.lbl_sld_pitch_2 = QLabel(self.grp_axes)
        self.lbl_sld_pitch_2.setObjectName(u"lbl_sld_pitch_2")
        self.lbl_sld_pitch_2.setGeometry(QRect(10, 20, 41, 16))
        self.lbl_sld_pitch_3 = QLabel(self.grp_axes)
        self.lbl_sld_pitch_3.setObjectName(u"lbl_sld_pitch_3")
        self.lbl_sld_pitch_3.setGeometry(QRect(90, 20, 41, 16))
        self.lbl_sld_pitch_4 = QLabel(self.grp_axes)
        self.lbl_sld_pitch_4.setObjectName(u"lbl_sld_pitch_4")
        self.lbl_sld_pitch_4.setEnabled(False)
        self.lbl_sld_pitch_4.setGeometry(QRect(190, 20, 31, 16))
        self.lbl_rig = QLabel(self.grp_axes)
        self.lbl_rig.setObjectName(u"lbl_rig")
        self.lbl_rig.setGeometry(QRect(310, 20, 151, 61))
        self.lbl_rig.setPixmap(QPixmap(u"images/rig.png"))
        self.groupBox_5 = QGroupBox(self.tab_main)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setEnabled(True)
        self.groupBox_5.setGeometry(QRect(480, 189, 141, 211))
        self.btn_motion_compensation_reload = QPushButton(self.groupBox_5)
        self.btn_motion_compensation_reload.setObjectName(u"btn_motion_compensation_reload")
        self.btn_motion_compensation_reload.setGeometry(QRect(10, 90, 121, 51))
        self.btn_motion_compensation_reload.setFont(font)
        self.btn_motion_compensation_reload.setCheckable(True)
        self.lbl_quest = QLabel(self.groupBox_5)
        self.lbl_quest.setObjectName(u"lbl_quest")
        self.lbl_quest.setGeometry(QRect(30, 20, 84, 61))
        self.lbl_quest.setPixmap(QPixmap(u"images/quest.png"))
        self.tabWidget.addTab(self.tab_main, "")
        self.tab_setting = QWidget()
        self.tab_setting.setObjectName(u"tab_setting")
        self.groupBox_3 = QGroupBox(self.tab_setting)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 0, 591, 161))
        self.txt_term_send = QLineEdit(self.groupBox_3)
        self.txt_term_send.setObjectName(u"txt_term_send")
        self.txt_term_send.setGeometry(QRect(12, 20, 201, 26))
        self.txt_term_send.setFont(font)
        self.btn_send = QPushButton(self.groupBox_3)
        self.btn_send.setObjectName(u"btn_send")
        self.btn_send.setGeometry(QRect(220, 20, 61, 26))
        self.btn_send.setFont(font)
        self.txt_term_rec = QTextBrowser(self.groupBox_3)
        self.txt_term_rec.setObjectName(u"txt_term_rec")
        self.txt_term_rec.setGeometry(QRect(10, 50, 571, 101))
        font3 = QFont()
        font3.setPointSize(8)
        self.txt_term_rec.setFont(font3)
        self.txt_term_rec.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.btn_clear = QPushButton(self.groupBox_3)
        self.btn_clear.setObjectName(u"btn_clear")
        self.btn_clear.setGeometry(QRect(290, 20, 61, 26))
        self.btn_clear.setFont(font)
        self.grp_pitch_axes = QGroupBox(self.tab_setting)
        self.grp_pitch_axes.setObjectName(u"grp_pitch_axes")
        self.grp_pitch_axes.setGeometry(QRect(30, 160, 571, 81))
        self.grp_pitch_axes.setFont(font)
        self.label_17 = QLabel(self.grp_pitch_axes)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(440, 50, 31, 22))
        self.txt_pitch_dem_low_knt = QLineEdit(self.grp_pitch_axes)
        self.txt_pitch_dem_low_knt.setObjectName(u"txt_pitch_dem_low_knt")
        self.txt_pitch_dem_low_knt.setGeometry(QRect(200, 50, 41, 22))
        self.txt_pitch_dem_hi_knt = QLineEdit(self.grp_pitch_axes)
        self.txt_pitch_dem_hi_knt.setObjectName(u"txt_pitch_dem_hi_knt")
        self.txt_pitch_dem_hi_knt.setGeometry(QRect(392, 50, 41, 22))
        self.txt_pitch_dem_hi_percent = QLineEdit(self.grp_pitch_axes)
        self.txt_pitch_dem_hi_percent.setObjectName(u"txt_pitch_dem_hi_percent")
        self.txt_pitch_dem_hi_percent.setGeometry(QRect(300, 50, 41, 22))
        self.label_8 = QLabel(self.grp_pitch_axes)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(150, 50, 51, 22))
        self.label_9 = QLabel(self.grp_pitch_axes)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(245, 50, 50, 22))
        self.txt_pitch_dem_low_percent = QLineEdit(self.grp_pitch_axes)
        self.txt_pitch_dem_low_percent.setObjectName(u"txt_pitch_dem_low_percent")
        self.txt_pitch_dem_low_percent.setGeometry(QRect(100, 50, 41, 22))
        self.label_16 = QLabel(self.grp_pitch_axes)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(344, 50, 51, 22))
        self.txt_pitch_factor = QLineEdit(self.grp_pitch_axes)
        self.txt_pitch_factor.setObjectName(u"txt_pitch_factor")
        self.txt_pitch_factor.setGeometry(QRect(100, 23, 41, 22))
        self.label_30 = QLabel(self.grp_pitch_axes)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 23, 91, 22))
        self.label_31 = QLabel(self.grp_pitch_axes)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 50, 91, 22))
        self.lbl_pitch_img = QLabel(self.grp_pitch_axes)
        self.lbl_pitch_img.setObjectName(u"lbl_pitch_img")
        self.lbl_pitch_img.setGeometry(QRect(484, 15, 80, 60))
        self.lbl_pitch_img.setPixmap(QPixmap(u"images/pitch_small.png"))
        self.ckb_pitch_axes = QCheckBox(self.tab_setting)
        self.ckb_pitch_axes.setObjectName(u"ckb_pitch_axes")
        self.ckb_pitch_axes.setGeometry(QRect(10, 200, 16, 22))
        self.ckb_pitch_axes.setChecked(True)
        self.grp_roll_axes = QGroupBox(self.tab_setting)
        self.grp_roll_axes.setObjectName(u"grp_roll_axes")
        self.grp_roll_axes.setGeometry(QRect(30, 240, 571, 81))
        self.grp_roll_axes.setFont(font)
        self.txt_roll_factor = QLineEdit(self.grp_roll_axes)
        self.txt_roll_factor.setObjectName(u"txt_roll_factor")
        self.txt_roll_factor.setGeometry(QRect(100, 23, 41, 22))
        self.label_33 = QLabel(self.grp_roll_axes)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 50, 91, 22))
        self.label_32 = QLabel(self.grp_roll_axes)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 23, 91, 22))
        self.label_34 = QLabel(self.grp_roll_axes)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(150, 50, 51, 22))
        self.label_35 = QLabel(self.grp_roll_axes)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(245, 50, 50, 22))
        self.label_36 = QLabel(self.grp_roll_axes)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(440, 50, 31, 22))
        self.label_37 = QLabel(self.grp_roll_axes)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(344, 50, 51, 22))
        self.txt_roll_dem_hi_knt = QLineEdit(self.grp_roll_axes)
        self.txt_roll_dem_hi_knt.setObjectName(u"txt_roll_dem_hi_knt")
        self.txt_roll_dem_hi_knt.setGeometry(QRect(392, 50, 41, 22))
        self.txt_roll_dem_low_knt = QLineEdit(self.grp_roll_axes)
        self.txt_roll_dem_low_knt.setObjectName(u"txt_roll_dem_low_knt")
        self.txt_roll_dem_low_knt.setGeometry(QRect(200, 50, 41, 22))
        self.txt_roll_dem_low_percent = QLineEdit(self.grp_roll_axes)
        self.txt_roll_dem_low_percent.setObjectName(u"txt_roll_dem_low_percent")
        self.txt_roll_dem_low_percent.setGeometry(QRect(100, 50, 41, 22))
        self.txt_roll_dem_hi_percent = QLineEdit(self.grp_roll_axes)
        self.txt_roll_dem_hi_percent.setObjectName(u"txt_roll_dem_hi_percent")
        self.txt_roll_dem_hi_percent.setGeometry(QRect(300, 50, 41, 22))
        self.lbl_roll_img = QLabel(self.grp_roll_axes)
        self.lbl_roll_img.setObjectName(u"lbl_roll_img")
        self.lbl_roll_img.setGeometry(QRect(484, 15, 80, 60))
        self.lbl_roll_img.setPixmap(QPixmap(u"images/roll_small.png"))
        self.grp_yaw_axes = QGroupBox(self.tab_setting)
        self.grp_yaw_axes.setObjectName(u"grp_yaw_axes")
        self.grp_yaw_axes.setEnabled(False)
        self.grp_yaw_axes.setGeometry(QRect(30, 320, 571, 81))
        self.grp_yaw_axes.setFont(font)
        self.txt_yaw_dem_hi_knt = QLineEdit(self.grp_yaw_axes)
        self.txt_yaw_dem_hi_knt.setObjectName(u"txt_yaw_dem_hi_knt")
        self.txt_yaw_dem_hi_knt.setGeometry(QRect(392, 50, 41, 22))
        self.txt_yaw_dem_low_knt = QLineEdit(self.grp_yaw_axes)
        self.txt_yaw_dem_low_knt.setObjectName(u"txt_yaw_dem_low_knt")
        self.txt_yaw_dem_low_knt.setGeometry(QRect(200, 50, 41, 22))
        self.txt_yaw_dem_hi_percent = QLineEdit(self.grp_yaw_axes)
        self.txt_yaw_dem_hi_percent.setObjectName(u"txt_yaw_dem_hi_percent")
        self.txt_yaw_dem_hi_percent.setGeometry(QRect(300, 50, 41, 22))
        self.txt_yaw_dem_low_percent = QLineEdit(self.grp_yaw_axes)
        self.txt_yaw_dem_low_percent.setObjectName(u"txt_yaw_dem_low_percent")
        self.txt_yaw_dem_low_percent.setGeometry(QRect(100, 50, 41, 22))
        self.label_42 = QLabel(self.grp_yaw_axes)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(440, 50, 31, 22))
        self.label_41 = QLabel(self.grp_yaw_axes)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(344, 50, 51, 22))
        self.label_38 = QLabel(self.grp_yaw_axes)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(150, 50, 51, 22))
        self.label_40 = QLabel(self.grp_yaw_axes)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(245, 50, 50, 22))
        self.label_39 = QLabel(self.grp_yaw_axes)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 23, 91, 22))
        self.label_43 = QLabel(self.grp_yaw_axes)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(10, 50, 91, 22))
        self.txt_yaw_factor = QLineEdit(self.grp_yaw_axes)
        self.txt_yaw_factor.setObjectName(u"txt_yaw_factor")
        self.txt_yaw_factor.setGeometry(QRect(100, 23, 41, 22))
        self.lbl_yaw_img = QLabel(self.grp_yaw_axes)
        self.lbl_yaw_img.setObjectName(u"lbl_yaw_img")
        self.lbl_yaw_img.setGeometry(QRect(484, 15, 80, 60))
        self.lbl_yaw_img.setPixmap(QPixmap(u"images/yaw_small.png"))
        self.ckb_roll_axes = QCheckBox(self.tab_setting)
        self.ckb_roll_axes.setObjectName(u"ckb_roll_axes")
        self.ckb_roll_axes.setGeometry(QRect(10, 270, 16, 22))
        self.ckb_roll_axes.setChecked(True)
        self.ckb_yaw_axes = QCheckBox(self.tab_setting)
        self.ckb_yaw_axes.setObjectName(u"ckb_yaw_axes")
        self.ckb_yaw_axes.setEnabled(False)
        self.ckb_yaw_axes.setGeometry(QRect(10, 350, 16, 22))
        self.ckb_yaw_axes.setMouseTracking(True)
        self.ckb_yaw_axes.setChecked(False)
        self.tabWidget.addTab(self.tab_setting, "")
        self.tab_interface = QWidget()
        self.tab_interface.setObjectName(u"tab_interface")
        self.groupBox_6 = QGroupBox(self.tab_interface)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 10, 591, 101))
        self.label = QLabel(self.groupBox_6)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(290, 30, 49, 22))
        self.label.setFont(font)
        self.label_2 = QLabel(self.groupBox_6)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(290, 60, 49, 22))
        self.label_2.setFont(font)
        self.txt_sim_ip = QLineEdit(self.groupBox_6)
        self.txt_sim_ip.setObjectName(u"txt_sim_ip")
        self.txt_sim_ip.setGeometry(QRect(370, 30, 113, 22))
        self.txt_sim_ip.setFont(font)
        self.txt_sim_ip.setInputMask(u"")
        self.txt_sim_port = QLineEdit(self.groupBox_6)
        self.txt_sim_port.setObjectName(u"txt_sim_port")
        self.txt_sim_port.setGeometry(QRect(370, 60, 113, 22))
        self.txt_sim_port.setFont(font)
        self.cmb_sim_software = QComboBox(self.groupBox_6)
        self.cmb_sim_software.addItem("")
        self.cmb_sim_software.addItem("")
        self.cmb_sim_software.setObjectName(u"cmb_sim_software")
        self.cmb_sim_software.setGeometry(QRect(10, 40, 221, 22))
        self.cmb_sim_software.setFont(font)
        self.groupBox_7 = QGroupBox(self.tab_interface)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 120, 281, 81))
        self.label_3 = QLabel(self.groupBox_7)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 30, 131, 22))
        self.label_3.setFont(font)
        self.cmb_serial_motion = QComboBox(self.groupBox_7)
        self.cmb_serial_motion.setObjectName(u"cmb_serial_motion")
        self.cmb_serial_motion.setGeometry(QRect(90, 30, 113, 22))
        self.cmb_serial_motion.setFont(font)
        self.groupBox_8 = QGroupBox(self.tab_interface)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(10, 210, 281, 151))
        self.cmb_serial_imu = QComboBox(self.groupBox_8)
        self.cmb_serial_imu.setObjectName(u"cmb_serial_imu")
        self.cmb_serial_imu.setGeometry(QRect(90, 40, 113, 22))
        self.cmb_serial_imu.setFont(font)
        self.label_18 = QLabel(self.groupBox_8)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 40, 81, 22))
        self.label_18.setFont(font)
        self.txt_mc_port = QLineEdit(self.groupBox_8)
        self.txt_mc_port.setObjectName(u"txt_mc_port")
        self.txt_mc_port.setGeometry(QRect(90, 100, 113, 22))
        self.txt_mc_port.setFont(font)
        self.label_22 = QLabel(self.groupBox_8)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 100, 49, 22))
        self.label_22.setFont(font)
        self.txt_mc_sensor_ip = QLineEdit(self.groupBox_8)
        self.txt_mc_sensor_ip.setObjectName(u"txt_mc_sensor_ip")
        self.txt_mc_sensor_ip.setGeometry(QRect(90, 70, 113, 22))
        self.txt_mc_sensor_ip.setFont(font)
        self.txt_mc_sensor_ip.setInputMask(u"")
        self.label_23 = QLabel(self.groupBox_8)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 70, 49, 22))
        self.label_23.setFont(font)
        self.tabWidget.addTab(self.tab_interface, "")
        self.label_14 = QLabel(SimMotion)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 530, 51, 16))
        self.lbl_status = QLabel(SimMotion)
        self.lbl_status.setObjectName(u"lbl_status")
        self.lbl_status.setGeometry(QRect(10, 551, 491, 41))
        self.btn_connect = QPushButton(SimMotion)
        self.btn_connect.setObjectName(u"btn_connect")
        self.btn_connect.setGeometry(QRect(10, 10, 121, 71))
        self.btn_connect.setFont(font)
        self.btn_connect.setCheckable(True)
        self.btn_quit = QPushButton(SimMotion)
        self.btn_quit.setObjectName(u"btn_quit")
        self.btn_quit.setGeometry(QRect(510, 540, 121, 31))
        self.btn_quit.setFont(font)

        self.retranslateUi(SimMotion)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(SimMotion)
    # setupUi

    def retranslateUi(self, SimMotion):
        SimMotion.setWindowTitle(QCoreApplication.translate("SimMotion", u"Form", None))
        self.btn_motion.setText(QCoreApplication.translate("SimMotion", u"motion", None))
        self.lbl_title.setText(QCoreApplication.translate("SimMotion", u"SimMotion", None))
        self.lbl_version.setText(QCoreApplication.translate("SimMotion", u"Version", None))
        self.lbl_logo.setText("")
        self.groupBox.setTitle(QCoreApplication.translate("SimMotion", u"simulator telemetry", None))
        self.label_7.setText(QCoreApplication.translate("SimMotion", u"speed [knt]:", None))
        self.label_10.setText(QCoreApplication.translate("SimMotion", u"update [Hz]:", None))
        self.label_5.setText(QCoreApplication.translate("SimMotion", u"roll [\u00b0]:", None))
        self.label_4.setText(QCoreApplication.translate("SimMotion", u"pitch [\u00b0]:", None))
        self.label_6.setText(QCoreApplication.translate("SimMotion", u"yaw [\u00b0]:", None))
        self.lbl_sim_pitch.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_sim_roll.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_sim_yaw.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_sim_speed.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_sim_update.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("SimMotion", u"motion telemetry", None))
        self.label_11.setText(QCoreApplication.translate("SimMotion", u"update [Hz]/time:", None))
        self.label_12.setText(QCoreApplication.translate("SimMotion", u"roll [\u00b0]/rate[\u00b0/s]:", None))
        self.label_13.setText(QCoreApplication.translate("SimMotion", u"pitch [\u00b0]/rate[\u00b0/s]:", None))
        self.label_15.setText(QCoreApplication.translate("SimMotion", u"yaw [\u00b0]/rate[\u00b0/s]:", None))
        self.lbl_motion_update.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_motion_timestamp.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_motion_pitch.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_motion_roll.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_motion_yaw.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_motion_pitch_rate.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_motion_roll_rate.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_motion_yaw_rate.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("SimMotion", u"current pose", None))
        self.label_19.setText(QCoreApplication.translate("SimMotion", u"roll [\u00b0]:", None))
        self.label_20.setText(QCoreApplication.translate("SimMotion", u"pitch [\u00b0]:", None))
        self.label_21.setText(QCoreApplication.translate("SimMotion", u"yaw [\u00b0]:", None))
        self.lbl_IMU_pitch.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_IMU_roll.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_IMU_yaw.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.grp_axes.setTitle(QCoreApplication.translate("SimMotion", u"Axes", None))
        self.lbl_sld_pitch.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_sld_roll.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.lbl_sld_yaw.setText(QCoreApplication.translate("SimMotion", u"180", None))
        self.btn_home.setText(QCoreApplication.translate("SimMotion", u"HOME", None))
        self.btn_axes.setText(QCoreApplication.translate("SimMotion", u"OFF", None))
        self.lbl_sld_pitch_2.setText(QCoreApplication.translate("SimMotion", u"PITCH", None))
        self.lbl_sld_pitch_3.setText(QCoreApplication.translate("SimMotion", u"ROLL", None))
        self.lbl_sld_pitch_4.setText(QCoreApplication.translate("SimMotion", u"YAW", None))
        self.lbl_rig.setText("")
        self.groupBox_5.setTitle(QCoreApplication.translate("SimMotion", u"Motion Comp.", None))
        self.btn_motion_compensation_reload.setText(QCoreApplication.translate("SimMotion", u"OFF", None))
        self.lbl_quest.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), QCoreApplication.translate("SimMotion", u"main", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("SimMotion", u"Terminal", None))
        self.txt_term_send.setText(QCoreApplication.translate("SimMotion", u"?;", None))
        self.btn_send.setText(QCoreApplication.translate("SimMotion", u"SEND", None))
        self.txt_term_rec.setHtml(QCoreApplication.translate("SimMotion", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">terminal response</p></body></html>", None))
        self.btn_clear.setText(QCoreApplication.translate("SimMotion", u"CLEAR", None))
        self.grp_pitch_axes.setTitle(QCoreApplication.translate("SimMotion", u"pitch axes", None))
        self.label_17.setText(QCoreApplication.translate("SimMotion", u"[knt]", None))
        self.txt_pitch_dem_low_knt.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.txt_pitch_dem_hi_knt.setText(QCoreApplication.translate("SimMotion", u"30", None))
        self.txt_pitch_dem_hi_percent.setText(QCoreApplication.translate("SimMotion", u"70", None))
        self.label_8.setText(QCoreApplication.translate("SimMotion", u"[%] @ ", None))
        self.label_9.setText(QCoreApplication.translate("SimMotion", u"[knt] -> ", None))
        self.txt_pitch_dem_low_percent.setText(QCoreApplication.translate("SimMotion", u"100", None))
        self.label_16.setText(QCoreApplication.translate("SimMotion", u"[%] @ ", None))
        self.txt_pitch_factor.setText(QCoreApplication.translate("SimMotion", u"3.2", None))
        self.label_30.setText(QCoreApplication.translate("SimMotion", u"factor", None))
        self.label_31.setText(QCoreApplication.translate("SimMotion", u"deminuator", None))
        self.lbl_pitch_img.setText("")
        self.ckb_pitch_axes.setText("")
        self.grp_roll_axes.setTitle(QCoreApplication.translate("SimMotion", u"roll axes", None))
        self.txt_roll_factor.setText(QCoreApplication.translate("SimMotion", u"3.2", None))
        self.label_33.setText(QCoreApplication.translate("SimMotion", u"deminuator", None))
        self.label_32.setText(QCoreApplication.translate("SimMotion", u"factor", None))
        self.label_34.setText(QCoreApplication.translate("SimMotion", u"[%] @ ", None))
        self.label_35.setText(QCoreApplication.translate("SimMotion", u"[knt] -> ", None))
        self.label_36.setText(QCoreApplication.translate("SimMotion", u"[knt]", None))
        self.label_37.setText(QCoreApplication.translate("SimMotion", u"[%] @ ", None))
        self.txt_roll_dem_hi_knt.setText(QCoreApplication.translate("SimMotion", u"30", None))
        self.txt_roll_dem_low_knt.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.txt_roll_dem_low_percent.setText(QCoreApplication.translate("SimMotion", u"100", None))
        self.txt_roll_dem_hi_percent.setText(QCoreApplication.translate("SimMotion", u"70", None))
        self.lbl_roll_img.setText("")
        self.grp_yaw_axes.setTitle(QCoreApplication.translate("SimMotion", u"yaw axes", None))
        self.txt_yaw_dem_hi_knt.setText(QCoreApplication.translate("SimMotion", u"180", None))
        self.txt_yaw_dem_low_knt.setText(QCoreApplication.translate("SimMotion", u"0", None))
        self.txt_yaw_dem_hi_percent.setText(QCoreApplication.translate("SimMotion", u"100", None))
        self.txt_yaw_dem_low_percent.setText(QCoreApplication.translate("SimMotion", u"100", None))
        self.label_42.setText(QCoreApplication.translate("SimMotion", u"[knt]", None))
        self.label_41.setText(QCoreApplication.translate("SimMotion", u"[%] @ ", None))
        self.label_38.setText(QCoreApplication.translate("SimMotion", u"[%] @ ", None))
        self.label_40.setText(QCoreApplication.translate("SimMotion", u"[knt] -> ", None))
        self.label_39.setText(QCoreApplication.translate("SimMotion", u"factor", None))
        self.label_43.setText(QCoreApplication.translate("SimMotion", u"deminuator", None))
        self.txt_yaw_factor.setText(QCoreApplication.translate("SimMotion", u"1", None))
        self.lbl_yaw_img.setText("")
        self.ckb_roll_axes.setText("")
        self.ckb_yaw_axes.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setting), QCoreApplication.translate("SimMotion", u"settings", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("SimMotion", u"Simulator", None))
        self.label.setText(QCoreApplication.translate("SimMotion", u"IP", None))
        self.label_2.setText(QCoreApplication.translate("SimMotion", u"PORT", None))
        self.txt_sim_ip.setText(QCoreApplication.translate("SimMotion", u"0.0.0.0", None))
        self.txt_sim_port.setText(QCoreApplication.translate("SimMotion", u"49001", None))
        self.cmb_sim_software.setItemText(0, QCoreApplication.translate("SimMotion", u"xplane", None))
        self.cmb_sim_software.setItemText(1, QCoreApplication.translate("SimMotion", u"msfs2024", None))

        self.groupBox_7.setTitle(QCoreApplication.translate("SimMotion", u"Motion platform", None))
        self.label_3.setText(QCoreApplication.translate("SimMotion", u"Teensy", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("SimMotion", u"Motion compensation", None))
        self.label_18.setText(QCoreApplication.translate("SimMotion", u"Sensor", None))
        self.txt_mc_port.setText(QCoreApplication.translate("SimMotion", u"4242", None))
        self.label_22.setText(QCoreApplication.translate("SimMotion", u"PORT", None))
        self.txt_mc_sensor_ip.setText(QCoreApplication.translate("SimMotion", u"127.0.0.1", None))
        self.label_23.setText(QCoreApplication.translate("SimMotion", u"IP", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_interface), QCoreApplication.translate("SimMotion", u"interfaces", None))
        self.label_14.setText(QCoreApplication.translate("SimMotion", u"status:", None))
        self.lbl_status.setText(QCoreApplication.translate("SimMotion", u"...", None))
        self.btn_connect.setText(QCoreApplication.translate("SimMotion", u"connect", None))
        self.btn_quit.setText(QCoreApplication.translate("SimMotion", u"quit", None))
    # retranslateUi

